### ISSUE TITLE
Feature: Create a footer component 

### ISSUE THREAD

**Issue by dev-phantom** [NOUNITE/nounite-frontend#20]
### Create a responsive footer using the figma file as a guide

**Comment by devtofunmi** [comment]
i'm unable to push to the branch i create for the footer component
![Screenshot 2023-02-16 235516](https://user-images.githubusercontent.com/98407328/219506736-5d4586b9-2f72-4add-8414-aa3dbf4b18db.png)

**Comment by dev-phantom** [comment]
> i'm unable to push to the branch i create for the footer component ![Screenshot 2023-02-16 235516](https://user-images.githubusercontent.com/98407328/219506736-5d4586b9-2f72-4add-8414-aa3dbf4b18db.png)


i doubt if you checked out of the main branch but if you did try using your cmd
`git checkout -b feat-footer`
`git init`
`git add .`
`git commit -m "your commit message"`
`git push origin feat-footer`
